### ISSUE TITLE
TC server url not being used fully by nuget server

### ISSUE THREAD

**Issue by aaron-0** [JetBrains/teamcity-nuget-support#17]
When "Server URL" is set the nuget servers url is correctly listed on the "Nuget Server" page.
However if you try to install a package using the feed and error will be returned. 
In the error message it will indicate that nuget is trying to use the local url.
e.g
local url http://localhost:8080/httpAuth/app/nuget/v1/FeedService.svc/
public url: https:/mydomain/httpAuth/app/nuget/v1/FeedService.svc/ (reverse proxy)
nuget list works obtaining list form mydomain.
nuget install fails with it trying to use http://llocalhost:8080 rather than https:/mydomain

**Comment by ekoshkin** [comment]
it's definatly an issue, thank you for reporting it, Will take a look on it.

**Comment by aaron-0** [comment]
Cheers, I ended up finding a work around in case any body else run into this.
Edit  TeamCiy\conf\server.xml
Add the following to the Connector element:
   proxyName="your.domain.com"
   proxyPort="443"
   secure="true"
   scheme="https"
This seems to have fixed the urls returned within the nuget feed to be as expected

**Comment by ekoshkin** [comment]
That is great!
