### ISSUE TITLE
Mutiple -Id in the custom command line parameters get incorrectly squashed into one

### ISSUE THREAD

**Issue by Necroskillz** [JetBrains/teamcity-nuget-support#22]
We have an update command set to update only specified packages. We do this by having `-Id package1 -Id package2 -Id package3` in the custom command line parameters. 

This worked fine in TC version `2018.1.3 (build 58658)` by passing the parameters to nuget as they were specified, but in `2018.2 (build 60925)` it passes the parameters to nuget like this: `-Id package1 package2 package3`, which causes nuget to only update the first package and ignore the others.

**Comment by dtretyakov** [comment]
@Necroskillz, thanks for reporting. It'll be fixed in the next TeamCity bug fix update 2018.2.1:
https://youtrack.jetbrains.com/issue/TW-58553
